changes:
    pom.xml
            changed  from
                <kettle.version>TRUNK-SNAPSHOT</kettle.version>
                        to
                <kettle.version>5.0.0</kettle.version>
                    reason:  easier to pull source files from known kettle release if we want to debug into them.

            Change some dependencies around,   otherwise, when we run we get:
                    java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory

                    also disabled provided for storm .jar's - else we get same run time error as above.
                    long term we should do this cleaner with a profile.

    testing:

        added org.testng dependency
        added integration tests on sample .ktr's

    TEMP FIX:
                added specialHandlingForJavaScript when we get signal that causes us to
                invoke processRows() for last row.  Gets around thread local issue.

                test that exercises this fix is:  KtrIntegrationTest.testWithJavaScriptStep()